version: v1.16.0.build{build}

init:
  - git config --global core.autocrlf true

install:
  - cinst -y nsis

matrix:
  fast_finish: true
  allow_failures:
    - platform: x86
      configuration: Release
    - platform: x64
      configuration: Release

environment:
  fast_finish: true
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VSVER: 12
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSVER: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSVER: 15
  
platform:
  - x86
  - x64

configuration:
  - Release

build_script:
  # Fixed tag version number if using a tag.
  - cmd: if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  # vcbuild overwrites the platform variable.
  - cmd: set ARCH=%platform%
  - cmd: vcbuild.bat release %ARCH% static
  - cmd: vcbuild.bat debug %ARCH% static  
  - ps: ls -r
  - rename c:\projects\libuv\Release\lib\libuv.lib mb_libuv_%VSVER%_%ARCH%_Release.lib
  - rename c:\projects\libuv\Debug\lib\libuv.lib mb_libuv_%VSVER%_%ARCH%_Debug.lib
  - appveyor PushArtifact c:\projects\libuv\Debug\lib\mb_libuv_%VSVER%_%ARCH%_Release.lib
  - appveyor PushArtifact c:\projects\libuv\Debug\lib\mb_libuv_%VSVER%_%ARCH%_Debug.lib
  
#after_build:
#  - '"%PROGRAMFILES(x86)%\NSIS\makensis" /DVERSION=%APPVEYOR_BUILD_VERSION% /DARCH=%ARCH% libuv.nsi'

#artifacts:
#  - name: Installer
#    path: 'libuv-*.exe'

cache:
  - C:\projects\libuv\build\gyp
