1;95;0cversion: 2
general:
  branches:
    only:
      - v1.x


jobs:
  android_all:
    docker:
      - image: centos:7.4.1708
    working_directory: ~/repo
    steps:
      - checkout
      - run: bash -e -x circleci_build_android.sh 
      - store_artifacts:
          path: /artifacts      
  centos7:
    docker:
      - image: centos:7.4.1708
    working_directory: ~/repo
    steps:
      - checkout
      - run: bash -e -x circleci_build.sh centos7.4.1708
      - store_artifacts:
          path: /artifacts

  centos6:
    docker:
      - image: centos:6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: bash -e -x circleci_build.sh centos6.9
      - store_artifacts:
          path: /artifacts

workflows:
 version: 2
 build_and_test:
   jobs:
     - centos7
     - centos6
     - android_all