version: 2
general:
  branches:
    only:
      - v1.x


jobs:
  build7:
    docker:
      - image: centos:7.4.1708
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh circleci_build.sh centos7.4.1708
      - store_artifacts:
          path: /artifacts

  build6:
    docker:
      - image: centos:6.9
    working_directory: ~/repo
    steps:
      - checkout
      - run: sh circleci_build.sh centos6.9
      - store_artifacts:
          path: /artifacts

workflows:
 version: 2
 build_and_test:
   jobs:
     - build7
     - build6